import { sql } from './sql.js';

export async function ensureDatabase() {
  await sql.query(`
    ALTER TABLE "user"
      ADD COLUMN IF NOT EXISTS role text NOT NULL DEFAULT 'user';

    ALTER TABLE "project"
      ADD COLUMN IF NOT EXISTS "githubUrl" text;

    ALTER TABLE "project"
      ADD COLUMN IF NOT EXISTS "demoUrl" text;

    CREATE TABLE IF NOT EXISTS "dailyNote" (
      id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      "userId" integer NOT NULL REFERENCES "user"(id) ON DELETE CASCADE,
      "studyDayId" integer NOT NULL REFERENCES "studyDay"(id) ON DELETE CASCADE,
      content text NOT NULL DEFAULT '',
      "createdAt" timestamptz NOT NULL DEFAULT now(),
      "updatedAt" timestamptz NOT NULL DEFAULT now(),
      CONSTRAINT "dailyNote_userId_studyDayId_key" UNIQUE ("userId", "studyDayId")
    );

    CREATE TABLE IF NOT EXISTS "notificationPreference" (
      id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      "userId" integer NOT NULL REFERENCES "user"(id) ON DELETE CASCADE,
      enabled boolean NOT NULL DEFAULT true,
      "reminderTime" time NOT NULL DEFAULT '08:00:00',
      timezone text NOT NULL DEFAULT 'UTC',
      "updatedAt" timestamptz NOT NULL DEFAULT now(),
      CONSTRAINT "notificationPreference_userId_key" UNIQUE ("userId")
    );

    CREATE TABLE IF NOT EXISTS "notification" (
      id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      "userId" integer NOT NULL REFERENCES "user"(id) ON DELETE CASCADE,
      type text NOT NULL,
      title text NOT NULL,
      message text NOT NULL,
      "isRead" boolean NOT NULL DEFAULT false,
      "createdAt" timestamptz NOT NULL DEFAULT now()
    );

    CREATE INDEX IF NOT EXISTS "notification_userId_createdAt_idx"
      ON "notification" ("userId", "createdAt" DESC);

    CREATE TABLE IF NOT EXISTS "achievement" (
      id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      code text NOT NULL UNIQUE,
      name text NOT NULL,
      description text NOT NULL,
      icon text NOT NULL DEFAULT '🏆'
    );

    CREATE TABLE IF NOT EXISTS "userAchievement" (
      id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      "userId" integer NOT NULL REFERENCES "user"(id) ON DELETE CASCADE,
      "achievementId" integer NOT NULL REFERENCES "achievement"(id) ON DELETE CASCADE,
      "unlockedAt" timestamptz NOT NULL DEFAULT now(),
      CONSTRAINT "userAchievement_userId_achievementId_key" UNIQUE ("userId", "achievementId")
    );

    CREATE TABLE IF NOT EXISTS "passwordResetToken" (
      id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      "userId" integer NOT NULL REFERENCES "user"(id) ON DELETE CASCADE,
      token_hash text NOT NULL UNIQUE,
      "expiresAt" timestamptz NOT NULL,
      "usedAt" timestamptz
    );

    CREATE INDEX IF NOT EXISTS "passwordResetToken_userId_idx"
      ON "passwordResetToken" ("userId");
  `);

  await sql.query(`
    INSERT INTO "achievement" (code, name, description, icon)
    VALUES
      ('FIRST_DAY', 'First Step', 'Complete your first study day.', '🌱'),
      ('THREE_DAYS', 'Three in a Row', 'Complete three study days.', '🔥'),
      ('SEVEN_DAY_STREAK', '7-Day Streak', 'Maintain a seven-day completion streak.', '🔥'),
      ('TEN_DAYS', 'Ten Down', 'Complete ten study days.', '🎯'),
      ('FIRST_PROJECT', 'Builder', 'Move a portfolio project above 0%.', '💻'),
      ('TWENTY_FIVE_PERCENT', 'Quarter Way', 'Reach 25% overall roadmap progress.', '🏆'),
      ('FIFTY_PERCENT', 'Halfway', 'Reach 50% overall roadmap progress.', '🏆'),
      ('ALL_DAYS', 'Roadmap Complete', 'Complete every study day.', '👑')
    ON CONFLICT (code) DO NOTHING;
  `);

  const adminEmail = process.env.ADMIN_EMAIL?.trim().toLowerCase();
  if (adminEmail) {
    await sql.query(`UPDATE "user" SET role = 'admin' WHERE lower(email) = $1`, [adminEmail]);
  }
}
