import "dotenv/config";
import { db } from "../prisma/db.js";

const studyDays = [
  { date: "2026-09-15T00:00:00Z", week: 1, phase: "JavaScript → TypeScript", focus: "Learn: JS fundamentals refresh, TypeScript types, interfaces, unions", practice: "Take notes, code examples yourself, then solve 2–3 small exercises.", projectTarget: "Small TS exercises + convert old JS snippets", hours: 3 },
  { date: "2026-09-16T00:00:00Z", week: 1, phase: "JavaScript → TypeScript", focus: "Practice: JS fundamentals refresh, TypeScript types, interfaces, unions", practice: "Implement a small feature without following a tutorial; debug and test it.", projectTarget: "Small TS exercises + convert old JS snippets", hours: 3 },
  { date: "2026-09-17T00:00:00Z", week: 1, phase: "JavaScript → TypeScript", focus: "Learn: JS fundamentals refresh, TypeScript types, interfaces, unions", practice: "Take notes, code examples yourself, then solve 2–3 small exercises.", projectTarget: "Small TS exercises + convert old JS snippets", hours: 3 },
  { date: "2026-09-18T00:00:00Z", week: 1, phase: "JavaScript → TypeScript", focus: "Practice: JS fundamentals refresh, TypeScript types, interfaces, unions", practice: "Implement a small feature without following a tutorial; debug and test it.", projectTarget: "Small TS exercises + convert old JS snippets", hours: 3 },
  { date: "2026-09-19T00:00:00Z", week: 1, phase: "JavaScript → TypeScript", focus: "Project-heavy day: JavaScript → TypeScript. Apply this week's concepts.", practice: "Build for 2–3 focused hours; fix bugs; commit to Git.", projectTarget: "Small TS exercises + convert old JS snippets", hours: 3 },
  { date: "2026-09-20T00:00:00Z", week: 1, phase: "Rest / Catch-up", focus: "Rest. If needed, review notes or finish one unfinished task.", practice: "Optional 30–60 min light review", projectTarget: "No new build work", hours: 0 },
  { date: "2026-09-21T00:00:00Z", week: 1, phase: "JavaScript → TypeScript", focus: "Practice: JS fundamentals refresh, TypeScript types, interfaces, unions", practice: "Implement a small feature without following a tutorial; debug and test it.", projectTarget: "Small TS exercises + convert old JS snippets", hours: 3 },
  { date: "2026-09-22T00:00:00Z", week: 2, phase: "TypeScript + React", focus: "Learn: Generics, utility types, hooks, component patterns", practice: "Take notes, code examples yourself, then solve 2–3 small exercises.", projectTarget: "Build reusable React components", hours: 3 },
  { date: "2026-09-23T00:00:00Z", week: 2, phase: "TypeScript + React", focus: "Practice: Generics, utility types, hooks, component patterns", practice: "Implement a small feature without following a tutorial; debug and test it.", projectTarget: "Build reusable React components", hours: 3 },
  { date: "2026-09-24T00:00:00Z", week: 2, phase: "TypeScript + React", focus: "Build: TypeScript + React", practice: "Apply the week's concept directly to the project; commit your work.", projectTarget: "Build reusable React components", hours: 3 },
  { date: "2026-09-25T00:00:00Z", week: 2, phase: "TypeScript + React", focus: "Learn: Generics, utility types, hooks, component patterns", practice: "Take notes, code examples yourself, then solve 2–3 small exercises.", projectTarget: "Build reusable React components", hours: 3 },
  { date: "2026-09-26T00:00:00Z", week: 2, phase: "TypeScript + React", focus: "Project-heavy day: TypeScript + React. Apply this week's concepts.", practice: "Build for 2–3 focused hours; fix bugs; commit to Git.", projectTarget: "Build reusable React components", hours: 3 },
  { date: "2026-09-27T00:00:00Z", week: 2, phase: "Rest / Catch-up", focus: "Rest. If needed, review notes or finish one unfinished task.", practice: "Optional 30–60 min light review", projectTarget: "No new build work", hours: 0 },
  { date: "2026-09-28T00:00:00Z", week: 2, phase: "TypeScript + React", focus: "Practice: Generics, utility types, hooks, component patterns", practice: "Implement a small feature without following a tutorial; debug and test it.", projectTarget: "Build reusable React components", hours: 3 },
  { date: "2026-09-29T00:00:00Z", week: 3, phase: "React", focus: "Build: React", practice: "Apply the week's concept directly to the project; commit your work.", projectTarget: "Build a small CRUD frontend", hours: 3 },
  { date: "2026-09-30T00:00:00Z", week: 3, phase: "React", focus: "Learn: State, forms, validation, data fetching, error/loading states", practice: "Take notes, code examples yourself, then solve 2–3 small exercises.", projectTarget: "Build a small CRUD frontend", hours: 3 },
  { date: "2026-10-01T00:00:00Z", week: 3, phase: "React", focus: "Practice: State, forms, validation, data fetching, error/loading states", practice: "Implement a small feature without following a tutorial; debug and test it.", projectTarget: "Build a small CRUD frontend", hours: 3 },
  { date: "2026-10-02T00:00:00Z", week: 3, phase: "React", focus: "Learn: State, forms, validation, data fetching, error/loading states", practice: "Take notes, code examples yourself, then solve 2–3 small exercises.", projectTarget: "Build a small CRUD frontend", hours: 3 },
  { date: "2026-10-03T00:00:00Z", week: 3, phase: "React", focus: "Project-heavy day: React. Apply this week's concepts.", practice: "Build for 2–3 focused hours; fix bugs; commit to Git.", projectTarget: "Build a small CRUD frontend", hours: 3 },
  { date: "2026-10-04T00:00:00Z", week: 3, phase: "Rest / Catch-up", focus: "Rest. If needed, review notes or finish one unfinished task.", practice: "Optional 30–60 min light review", projectTarget: "No new build work", hours: 0 },
  { date: "2026-10-05T00:00:00Z", week: 3, phase: "React", focus: "Learn: State, forms, validation, data fetching, error/loading states", practice: "Take notes, code examples yourself, then solve 2–3 small exercises.", projectTarget: "Build a small CRUD frontend", hours: 3 },
  { date: "2026-10-06T00:00:00Z", week: 4, phase: "Next.js", focus: "Practice: Routing, layouts, server/client components, API routes, SEO basics", practice: "Implement a small feature without following a tutorial; debug and test it.", projectTarget: "Start Inventory System", hours: 3 },
  { date: "2026-10-07T00:00:00Z", week: 4, phase: "Next.js", focus: "Learn: Routing, layouts, server/client components, API routes, SEO basics", practice: "Take notes, code examples yourself, then solve 2–3 small exercises.", projectTarget: "Start Inventory System", hours: 3 },
  { date: "2026-10-08T00:00:00Z", week: 4, phase: "Next.js", focus: "Practice: Routing, layouts, server/client components, API routes, SEO basics", practice: "Implement a small feature without following a tutorial; debug and test it.", projectTarget: "Start Inventory System", hours: 3 },
  { date: "2026-10-09T00:00:00Z", week: 4, phase: "Next.js", focus: "Build: Next.js", practice: "Apply the week's concept directly to the project; commit your work.", projectTarget: "Start Inventory System", hours: 3 },
  { date: "2026-10-10T00:00:00Z", week: 4, phase: "Next.js", focus: "Project-heavy day: Next.js. Apply this week's concepts.", practice: "Build for 2–3 focused hours; fix bugs; commit to Git.", projectTarget: "Start Inventory System", hours: 3 },
  { date: "2026-10-11T00:00:00Z", week: 4, phase: "Rest / Catch-up", focus: "Rest. If needed, review notes or finish one unfinished task.", practice: "Optional 30–60 min light review", projectTarget: "No new build work", hours: 0 },
  { date: "2026-10-12T00:00:00Z", week: 4, phase: "Next.js", focus: "Learn: Routing, layouts, server/client components, API routes, SEO basics", practice: "Take notes, code examples yourself, then solve 2–3 small exercises.", projectTarget: "Start Inventory System", hours: 3 },
  { date: "2026-10-13T00:00:00Z", week: 5, phase: "Node.js", focus: "Practice: Node runtime, modules, async patterns, environment variables", practice: "Implement a small feature without following a tutorial; debug and test it.", projectTarget: "Build small Node services", hours: 3 },
  { date: "2026-10-14T00:00:00Z", week: 5, phase: "Node.js", focus: "Build: Node.js", practice: "Apply the week's concept directly to the project; commit your work.", projectTarget: "Build small Node services", hours: 3 },
  { date: "2026-10-15T00:00:00Z", week: 5, phase: "Node.js", focus: "Learn: Node runtime, modules, async patterns, environment variables", practice: "Take notes, code examples yourself, then solve 2–3 small exercises.", projectTarget: "Build small Node services", hours: 3 },
  { date: "2026-10-16T00:00:00Z", week: 5, phase: "Node.js", focus: "Practice: Node runtime, modules, async patterns, environment variables", practice: "Implement a small feature without following a tutorial; debug and test it.", projectTarget: "Build small Node services", hours: 3 },
  { date: "2026-10-17T00:00:00Z", week: 5, phase: "Node.js", focus: "Project-heavy day: Node.js. Apply this week's concepts.", practice: "Build for 2–3 focused hours; fix bugs; commit to Git.", projectTarget: "Build small Node services", hours: 3 },
  { date: "2026-10-18T00:00:00Z", week: 5, phase: "Rest / Catch-up", focus: "Rest. If needed, review notes or finish one unfinished task.", practice: "Optional 30–60 min light review", projectTarget: "No new build work", hours: 0 },
  { date: "2026-10-19T00:00:00Z", week: 5, phase: "Node.js", focus: "Build: Node.js", practice: "Apply the week's concept directly to the project; commit your work.", projectTarget: "Build small Node services", hours: 3 },
  { date: "2026-10-20T00:00:00Z", week: 6, phase: "Express", focus: "Learn: Routes, middleware, validation, error handling, REST design", practice: "Take notes, code examples yourself, then solve 2–3 small exercises.", projectTarget: "Inventory API foundation", hours: 3 },
  { date: "2026-10-21T00:00:00Z", week: 6, phase: "Express", focus: "Practice: Routes, middleware, validation, error handling, REST design", practice: "Implement a small feature without following a tutorial; debug and test it.", projectTarget: "Inventory API foundation", hours: 3 },
  { date: "2026-10-22T00:00:00Z", week: 6, phase: "Express", focus: "Learn: Routes, middleware, validation, error handling, REST design", practice: "Take notes, code examples yourself, then solve 2–3 small exercises.", projectTarget: "Inventory API foundation", hours: 3 },
  { date: "2026-10-23T00:00:00Z", week: 6, phase: "Express", focus: "Practice: Routes, middleware, validation, error handling, REST design", practice: "Implement a small feature without following a tutorial; debug and test it.", projectTarget: "Inventory API foundation", hours: 3 },
  { date: "2026-10-24T00:00:00Z", week: 6, phase: "Express", focus: "Project-heavy day: Express. Apply this week's concepts.", practice: "Build for 2–3 focused hours; fix bugs; commit to Git.", projectTarget: "Inventory API foundation", hours: 3 },
  { date: "2026-10-25T00:00:00Z", week: 6, phase: "Rest / Catch-up", focus: "Rest. If needed, review notes or finish one unfinished task.", practice: "Optional 30–60 min light review", projectTarget: "No new build work", hours: 0 },
  { date: "2026-10-26T00:00:00Z", week: 6, phase: "Express", focus: "Practice: Routes, middleware, validation, error handling, REST design", practice: "Implement a small feature without following a tutorial; debug and test it.", projectTarget: "Inventory API foundation", hours: 3 },
  { date: "2026-10-27T00:00:00Z", week: 7, phase: "PostgreSQL", focus: "Learn: SQL, relationships, indexes, constraints, transactions", practice: "Take notes, code examples yourself, then solve 2–3 small exercises.", projectTarget: "Design Inventory database", hours: 3 },
  { date: "2026-10-28T00:00:00Z", week: 7, phase: "PostgreSQL", focus: "Practice: SQL, relationships, indexes, constraints, transactions", practice: "Implement a small feature without following a tutorial; debug and test it.", projectTarget: "Design Inventory database", hours: 3 },
  { date: "2026-10-29T00:00:00Z", week: 7, phase: "PostgreSQL", focus: "Build: PostgreSQL", practice: "Apply the week's concept directly to the project; commit your work.", projectTarget: "Design Inventory database", hours: 3 },
  { date: "2026-10-30T00:00:00Z", week: 7, phase: "PostgreSQL", focus: "Learn: SQL, relationships, indexes, constraints, transactions", practice: "Take notes, code examples yourself, then solve 2–3 small exercises.", projectTarget: "Design Inventory database", hours: 3 },
  { date: "2026-10-31T00:00:00Z", week: 7, phase: "PostgreSQL", focus: "Project-heavy day: PostgreSQL. Apply this week's concepts.", practice: "Build for 2–3 focused hours; fix bugs; commit to Git.", projectTarget: "Design Inventory database", hours: 3 },
  { date: "2026-11-01T00:00:00Z", week: 7, phase: "Rest / Catch-up", focus: "Rest. If needed, review notes or finish one unfinished task.", practice: "Optional 30–60 min light review", projectTarget: "No new build work", hours: 0 },
  { date: "2026-11-02T00:00:00Z", week: 7, phase: "PostgreSQL", focus: "Practice: SQL, relationships, indexes, constraints, transactions", practice: "Implement a small feature without following a tutorial; debug and test it.", projectTarget: "Design Inventory database", hours: 3 },
  { date: "2026-11-03T00:00:00Z", week: 8, phase: "Auth + Backend", focus: "Build: Auth + Backend", practice: "Apply the week's concept directly to the project; commit your work.", projectTarget: "Complete inventory authentication", hours: 3 },
  { date: "2026-11-04T00:00:00Z", week: 8, phase: "Auth + Backend", focus: "Learn: JWT, bcrypt, roles/RBAC, protected routes", practice: "Take notes, code examples yourself, then solve 2–3 small exercises.", projectTarget: "Complete inventory authentication", hours: 3 },
  { date: "2026-11-05T00:00:00Z", week: 8, phase: "Auth + Backend", focus: "Practice: JWT, bcrypt, roles/RBAC, protected routes", practice: "Implement a small feature without following a tutorial; debug and test it.", projectTarget: "Complete inventory authentication", hours: 3 },
  { date: "2026-11-06T00:00:00Z", week: 8, phase: "Auth + Backend", focus: "Learn: JWT, bcrypt, roles/RBAC, protected routes", practice: "Take notes, code examples yourself, then solve 2–3 small exercises.", projectTarget: "Complete inventory authentication", hours: 3 },
  { date: "2026-11-07T00:00:00Z", week: 8, phase: "Auth + Backend", focus: "Project-heavy day: Auth + Backend. Apply this week's concepts.", practice: "Build for 2–3 focused hours; fix bugs; commit to Git.", projectTarget: "Complete inventory authentication", hours: 3 },
  { date: "2026-11-08T00:00:00Z", week: 8, phase: "Rest / Catch-up", focus: "Rest. If needed, review notes or finish one unfinished task.", practice: "Optional 30–60 min light review", projectTarget: "No new build work", hours: 0 },
  { date: "2026-11-09T00:00:00Z", week: 8, phase: "Auth + Backend", focus: "Learn: JWT, bcrypt, roles/RBAC, protected routes", practice: "Take notes, code examples yourself, then solve 2–3 small exercises.", projectTarget: "Complete inventory authentication", hours: 3 },
  { date: "2026-11-10T00:00:00Z", week: 9, phase: "Inventory System", focus: "Practice: Sales, stock, purchases, profit/loss, credit ledger", practice: "Implement a small feature without following a tutorial; debug and test it.", projectTarget: "Build core inventory features", hours: 3 },
  { date: "2026-11-11T00:00:00Z", week: 9, phase: "Inventory System", focus: "Learn: Sales, stock, purchases, profit/loss, credit ledger", practice: "Take notes, code examples yourself, then solve 2–3 small exercises.", projectTarget: "Build core inventory features", hours: 3 },
  { date: "2026-11-12T00:00:00Z", week: 9, phase: "Inventory System", focus: "Practice: Sales, stock, purchases, profit/loss, credit ledger", practice: "Implement a small feature without following a tutorial; debug and test it.", projectTarget: "Build core inventory features", hours: 3 },
  { date: "2026-11-13T00:00:00Z", week: 9, phase: "Inventory System", focus: "Build: Inventory System", practice: "Apply the week's concept directly to the project; commit your work.", projectTarget: "Build core inventory features", hours: 3 },
  { date: "2026-11-14T00:00:00Z", week: 9, phase: "Inventory System", focus: "Project-heavy day: Inventory System. Apply this week's concepts.", practice: "Build for 2–3 focused hours; fix bugs; commit to Git.", projectTarget: "Build core inventory features", hours: 3 },
  { date: "2026-11-15T00:00:00Z", week: 9, phase: "Rest / Catch-up", focus: "Rest. If needed, review notes or finish one unfinished task.", practice: "Optional 30–60 min light review", projectTarget: "No new build work", hours: 0 },
  { date: "2026-11-16T00:00:00Z", week: 9, phase: "Inventory System", focus: "Learn: Sales, stock, purchases, profit/loss, credit ledger", practice: "Take notes, code examples yourself, then solve 2–3 small exercises.", projectTarget: "Build core inventory features", hours: 3 },
  { date: "2026-11-17T00:00:00Z", week: 10, phase: "Inventory System", focus: "Practice: Dashboard, charts, notifications, image/product workflow", practice: "Implement a small feature without following a tutorial; debug and test it.", projectTarget: "Finish inventory frontend", hours: 3 },
  { date: "2026-11-18T00:00:00Z", week: 10, phase: "Inventory System", focus: "Build: Inventory System", practice: "Apply the week's concept directly to the project; commit your work.", projectTarget: "Finish inventory frontend", hours: 3 },
  { date: "2026-11-19T00:00:00Z", week: 10, phase: "Inventory System", focus: "Learn: Dashboard, charts, notifications, image/product workflow", practice: "Take notes, code examples yourself, then solve 2–3 small exercises.", projectTarget: "Finish inventory frontend", hours: 3 },
  { date: "2026-11-20T00:00:00Z", week: 10, phase: "Inventory System", focus: "Practice: Dashboard, charts, notifications, image/product workflow", practice: "Implement a small feature without following a tutorial; debug and test it.", projectTarget: "Finish inventory frontend", hours: 3 },
  { date: "2026-11-21T00:00:00Z", week: 10, phase: "Inventory System", focus: "Project-heavy day: Inventory System. Apply this week's concepts.", practice: "Build for 2–3 focused hours; fix bugs; commit to Git.", projectTarget: "Finish inventory frontend", hours: 3 },
  { date: "2026-11-22T00:00:00Z", week: 10, phase: "Rest / Catch-up", focus: "Rest. If needed, review notes or finish one unfinished task.", practice: "Optional 30–60 min light review", projectTarget: "No new build work", hours: 0 },
  { date: "2026-11-23T00:00:00Z", week: 10, phase: "Inventory System", focus: "Build: Inventory System", practice: "Apply the week's concept directly to the project; commit your work.", projectTarget: "Finish inventory frontend", hours: 3 },
  { date: "2026-11-24T00:00:00Z", week: 11, phase: "Deployment", focus: "Learn: Git/GitHub, environment variables, deployment, logging", practice: "Take notes, code examples yourself, then solve 2–3 small exercises.", projectTarget: "Deploy Inventory System", hours: 3 },
  { date: "2026-11-25T00:00:00Z", week: 11, phase: "Deployment", focus: "Practice: Git/GitHub, environment variables, deployment, logging", practice: "Implement a small feature without following a tutorial; debug and test it.", projectTarget: "Deploy Inventory System", hours: 3 },
  { date: "2026-11-26T00:00:00Z", week: 11, phase: "Deployment", focus: "Learn: Git/GitHub, environment variables, deployment, logging", practice: "Take notes, code examples yourself, then solve 2–3 small exercises.", projectTarget: "Deploy Inventory System", hours: 3 },
  { date: "2026-11-27T00:00:00Z", week: 11, phase: "Deployment", focus: "Practice: Git/GitHub, environment variables, deployment, logging", practice: "Implement a small feature without following a tutorial; debug and test it.", projectTarget: "Deploy Inventory System", hours: 3 },
  { date: "2026-11-28T00:00:00Z", week: 11, phase: "Deployment", focus: "Project-heavy day: Deployment. Apply this week's concepts.", practice: "Build for 2–3 focused hours; fix bugs; commit to Git.", projectTarget: "Deploy Inventory System", hours: 3 },
  { date: "2026-11-29T00:00:00Z", week: 11, phase: "Rest / Catch-up", focus: "Rest. If needed, review notes or finish one unfinished task.", practice: "Optional 30–60 min light review", projectTarget: "No new build work", hours: 0 },
  { date: "2026-11-30T00:00:00Z", week: 11, phase: "Deployment", focus: "Practice: Git/GitHub, environment variables, deployment, logging", practice: "Implement a small feature without following a tutorial; debug and test it.", projectTarget: "Deploy Inventory System", hours: 3 },
  { date: "2026-12-01T00:00:00Z", week: 12, phase: "Testing", focus: "Learn: Unit/integration testing, API testing, edge cases", practice: "Take notes, code examples yourself, then solve 2–3 small exercises.", projectTarget: "Test inventory + fix issues", hours: 3 },
  { date: "2026-12-02T00:00:00Z", week: 12, phase: "Testing", focus: "Practice: Unit/integration testing, API testing, edge cases", practice: "Implement a small feature without following a tutorial; debug and test it.", projectTarget: "Test inventory + fix issues", hours: 3 },
  { date: "2026-12-03T00:00:00Z", week: 12, phase: "Testing", focus: "Build: Testing", practice: "Apply the week's concept directly to the project; commit your work.", projectTarget: "Test inventory + fix issues", hours: 3 },
  { date: "2026-12-04T00:00:00Z", week: 12, phase: "Testing", focus: "Learn: Unit/integration testing, API testing, edge cases", practice: "Take notes, code examples yourself, then solve 2–3 small exercises.", projectTarget: "Test inventory + fix issues", hours: 3 },
  { date: "2026-12-05T00:00:00Z", week: 12, phase: "Testing", focus: "Project-heavy day: Testing. Apply this week's concepts.", practice: "Build for 2–3 focused hours; fix bugs; commit to Git.", projectTarget: "Test inventory + fix issues", hours: 3 },
  { date: "2026-12-06T00:00:00Z", week: 12, phase: "Rest / Catch-up", focus: "Rest. If needed, review notes or finish one unfinished task.", practice: "Optional 30–60 min light review", projectTarget: "No new build work", hours: 0 },
  { date: "2026-12-07T00:00:00Z", week: 12, phase: "Testing", focus: "Practice: Unit/integration testing, API testing, edge cases", practice: "Implement a small feature without following a tutorial; debug and test it.", projectTarget: "Test inventory + fix issues", hours: 3 },
  { date: "2026-12-08T00:00:00Z", week: 13, phase: "Docker + CI/CD", focus: "Build: Docker + CI/CD", practice: "Apply the week's concept directly to the project; commit your work.", projectTarget: "Containerize and automate tests", hours: 3 },
  { date: "2026-12-09T00:00:00Z", week: 13, phase: "Docker + CI/CD", focus: "Learn: Docker basics, Docker Compose, GitHub Actions", practice: "Take notes, code examples yourself, then solve 2–3 small exercises.", projectTarget: "Containerize and automate tests", hours: 3 },
  { date: "2026-12-10T00:00:00Z", week: 13, phase: "Docker + CI/CD", focus: "Practice: Docker basics, Docker Compose, GitHub Actions", practice: "Implement a small feature without following a tutorial; debug and test it.", projectTarget: "Containerize and automate tests", hours: 3 },
  { date: "2026-12-11T00:00:00Z", week: 13, phase: "Docker + CI/CD", focus: "Learn: Docker basics, Docker Compose, GitHub Actions", practice: "Take notes, code examples yourself, then solve 2–3 small exercises.", projectTarget: "Containerize and automate tests", hours: 3 },
  { date: "2026-12-12T00:00:00Z", week: 13, phase: "Docker + CI/CD", focus: "Project-heavy day: Docker + CI/CD. Apply this week's concepts.", practice: "Build for 2–3 focused hours; fix bugs; commit to Git.", projectTarget: "Containerize and automate tests", hours: 3 },
  { date: "2026-12-13T00:00:00Z", week: 13, phase: "Rest / Catch-up", focus: "Rest. If needed, review notes or finish one unfinished task.", practice: "Optional 30–60 min light review", projectTarget: "No new build work", hours: 0 },
  { date: "2026-12-14T00:00:00Z", week: 13, phase: "Docker + CI/CD", focus: "Learn: Docker basics, Docker Compose, GitHub Actions", practice: "Take notes, code examples yourself, then solve 2–3 small exercises.", projectTarget: "Containerize and automate tests", hours: 3 },
  { date: "2026-12-15T00:00:00Z", week: 14, phase: "AWS + Security", focus: "Practice: AWS fundamentals, hosting concepts, security checklist", practice: "Implement a small feature without following a tutorial; debug and test it.", projectTarget: "Deploy/experiment with AWS", hours: 3 },
  { date: "2026-12-16T00:00:00Z", week: 14, phase: "AWS + Security", focus: "Learn: AWS fundamentals, hosting concepts, security checklist", practice: "Take notes, code examples yourself, then solve 2–3 small exercises.", projectTarget: "Deploy/experiment with AWS", hours: 3 },
  { date: "2026-12-17T00:00:00Z", week: 14, phase: "AWS + Security", focus: "Practice: AWS fundamentals, hosting concepts, security checklist", practice: "Implement a small feature without following a tutorial; debug and test it.", projectTarget: "Deploy/experiment with AWS", hours: 3 },
  { date: "2026-12-18T00:00:00Z", week: 14, phase: "AWS + Security", focus: "Build: AWS + Security", practice: "Apply the week's concept directly to the project; commit your work.", projectTarget: "Deploy/experiment with AWS", hours: 3 },
  { date: "2026-12-19T00:00:00Z", week: 14, phase: "AWS + Security", focus: "Project-heavy day: AWS + Security. Apply this week's concepts.", practice: "Build for 2–3 focused hours; fix bugs; commit to Git.", projectTarget: "Deploy/experiment with AWS", hours: 3 },
  { date: "2026-12-20T00:00:00Z", week: 14, phase: "Rest / Catch-up", focus: "Rest. If needed, review notes or finish one unfinished task.", practice: "Optional 30–60 min light review", projectTarget: "No new build work", hours: 0 },
  { date: "2026-12-21T00:00:00Z", week: 14, phase: "AWS + Security", focus: "Learn: AWS fundamentals, hosting concepts, security checklist", practice: "Take notes, code examples yourself, then solve 2–3 small exercises.", projectTarget: "Deploy/experiment with AWS", hours: 3 },
  { date: "2026-12-22T00:00:00Z", week: 15, phase: "Ticketing Platform", focus: "Practice: Architecture, schema, ticket categories, accounts", practice: "Implement a small feature without following a tutorial; debug and test it.", projectTarget: "Start Alumni Ticketing Platform", hours: 3 },
  { date: "2026-12-23T00:00:00Z", week: 15, phase: "Ticketing Platform", focus: "Build: Ticketing Platform", practice: "Apply the week's concept directly to the project; commit your work.", projectTarget: "Start Alumni Ticketing Platform", hours: 3 },
  { date: "2026-12-24T00:00:00Z", week: 15, phase: "Ticketing Platform", focus: "Learn: Architecture, schema, ticket categories, accounts", practice: "Take notes, code examples yourself, then solve 2–3 small exercises.", projectTarget: "Start Alumni Ticketing Platform", hours: 3 },
  { date: "2026-12-25T00:00:00Z", week: 15, phase: "Ticketing Platform", focus: "Practice: Architecture, schema, ticket categories, accounts", practice: "Implement a small feature without following a tutorial; debug and test it.", projectTarget: "Start Alumni Ticketing Platform", hours: 3 },
  { date: "2026-12-26T00:00:00Z", week: 15, phase: "Ticketing Platform", focus: "Project-heavy day: Ticketing Platform. Apply this week's concepts.", practice: "Build for 2–3 focused hours; fix bugs; commit to Git.", projectTarget: "Start Alumni Ticketing Platform", hours: 3 },
  { date: "2026-12-27T00:00:00Z", week: 15, phase: "Rest / Catch-up", focus: "Rest. If needed, review notes or finish one unfinished task.", practice: "Optional 30–60 min light review", projectTarget: "No new build work", hours: 0 },
  { date: "2026-12-28T00:00:00Z", week: 15, phase: "Ticketing Platform", focus: "Build: Ticketing Platform", practice: "Apply the week's concept directly to the project; commit your work.", projectTarget: "Start Alumni Ticketing Platform", hours: 3 },
  { date: "2026-12-29T00:00:00Z", week: 16, phase: "Ticketing Platform", focus: "Learn: Payments, ticket generation, QR codes", practice: "Take notes, code examples yourself, then solve 2–3 small exercises.", projectTarget: "Implement payment + ticket flow", hours: 3 },
  { date: "2026-12-30T00:00:00Z", week: 16, phase: "Ticketing Platform", focus: "Practice: Payments, ticket generation, QR codes", practice: "Implement a small feature without following a tutorial; debug and test it.", projectTarget: "Implement payment + ticket flow", hours: 3 },
  { date: "2026-12-31T00:00:00Z", week: 16, phase: "Ticketing Platform", focus: "Learn: Payments, ticket generation, QR codes", practice: "Take notes, code examples yourself, then solve 2–3 small exercises.", projectTarget: "Implement payment + ticket flow", hours: 3 },
  { date: "2027-01-01T00:00:00Z", week: 16, phase: "Ticketing Platform", focus: "Practice: Payments, ticket generation, QR codes", practice: "Implement a small feature without following a tutorial; debug and test it.", projectTarget: "Implement payment + ticket flow", hours: 3 },
  { date: "2027-01-02T00:00:00Z", week: 16, phase: "Ticketing Platform", focus: "Project-heavy day: Ticketing Platform. Apply this week's concepts.", practice: "Build for 2–3 focused hours; fix bugs; commit to Git.", projectTarget: "Implement payment + ticket flow", hours: 3 },
  { date: "2027-01-03T00:00:00Z", week: 16, phase: "Rest / Catch-up", focus: "Rest. If needed, review notes or finish one unfinished task.", practice: "Optional 30–60 min light review", projectTarget: "No new build work", hours: 0 },
  { date: "2027-01-04T00:00:00Z", week: 16, phase: "Ticketing Platform", focus: "Practice: Payments, ticket generation, QR codes", practice: "Implement a small feature without following a tutorial; debug and test it.", projectTarget: "Implement payment + ticket flow", hours: 3 },
  { date: "2027-01-05T00:00:00Z", week: 17, phase: "Ticketing Platform", focus: "Learn: QR verification, admin dashboard, analytics", practice: "Take notes, code examples yourself, then solve 2–3 small exercises.", projectTarget: "Complete admin + verification", hours: 3 },
  { date: "2027-01-06T00:00:00Z", week: 17, phase: "Ticketing Platform", focus: "Practice: QR verification, admin dashboard, analytics", practice: "Implement a small feature without following a tutorial; debug and test it.", projectTarget: "Complete admin + verification", hours: 3 },
  { date: "2027-01-07T00:00:00Z", week: 17, phase: "Ticketing Platform", focus: "Build: Ticketing Platform", practice: "Apply the week's concept directly to the project; commit your work.", projectTarget: "Complete admin + verification", hours: 3 },
  { date: "2027-01-08T00:00:00Z", week: 17, phase: "Ticketing Platform", focus: "Learn: QR verification, admin dashboard, analytics", practice: "Take notes, code examples yourself, then solve 2–3 small exercises.", projectTarget: "Complete admin + verification", hours: 3 },
  { date: "2027-01-09T00:00:00Z", week: 17, phase: "Ticketing Platform", focus: "Project-heavy day: Ticketing Platform. Apply this week's concepts.", practice: "Build for 2–3 focused hours; fix bugs; commit to Git.", projectTarget: "Complete admin + verification", hours: 3 },
  { date: "2027-01-10T00:00:00Z", week: 17, phase: "Rest / Catch-up", focus: "Rest. If needed, review notes or finish one unfinished task.", practice: "Optional 30–60 min light review", projectTarget: "No new build work", hours: 0 },
  { date: "2027-01-11T00:00:00Z", week: 17, phase: "Ticketing Platform", focus: "Practice: QR verification, admin dashboard, analytics", practice: "Implement a small feature without following a tutorial; debug and test it.", projectTarget: "Complete admin + verification", hours: 3 },
  { date: "2027-01-12T00:00:00Z", week: 18, phase: "Ticketing Platform", focus: "Build: Ticketing Platform", practice: "Apply the week's concept directly to the project; commit your work.", projectTarget: "Deploy portfolio-ready version", hours: 3 },
  { date: "2027-01-13T00:00:00Z", week: 18, phase: "Ticketing Platform", focus: "Learn: Testing, deployment, polish, documentation", practice: "Take notes, code examples yourself, then solve 2–3 small exercises.", projectTarget: "Deploy portfolio-ready version", hours: 3 },
  { date: "2027-01-14T00:00:00Z", week: 18, phase: "Ticketing Platform", focus: "Practice: Testing, deployment, polish, documentation", practice: "Implement a small feature without following a tutorial; debug and test it.", projectTarget: "Deploy portfolio-ready version", hours: 3 },
  { date: "2027-01-15T00:00:00Z", week: 18, phase: "Ticketing Platform", focus: "Learn: Testing, deployment, polish, documentation", practice: "Take notes, code examples yourself, then solve 2–3 small exercises.", projectTarget: "Deploy portfolio-ready version", hours: 3 },
  { date: "2027-01-16T00:00:00Z", week: 18, phase: "Ticketing Platform", focus: "Project-heavy day: Ticketing Platform. Apply this week's concepts.", practice: "Build for 2–3 focused hours; fix bugs; commit to Git.", projectTarget: "Deploy portfolio-ready version", hours: 3 },
  { date: "2027-01-17T00:00:00Z", week: 18, phase: "Rest / Catch-up", focus: "Rest. If needed, review notes or finish one unfinished task.", practice: "Optional 30–60 min light review", projectTarget: "No new build work", hours: 0 },
  { date: "2027-01-18T00:00:00Z", week: 18, phase: "Ticketing Platform", focus: "Learn: Testing, deployment, polish, documentation", practice: "Take notes, code examples yourself, then solve 2–3 small exercises.", projectTarget: "Deploy portfolio-ready version", hours: 3 },
  { date: "2027-01-19T00:00:00Z", week: 19, phase: "Payments + PDFs", focus: "Practice: Stripe/payment concepts, PDF generation, document workflows", practice: "Implement a small feature without following a tutorial; debug and test it.", projectTarget: "Start Will/Document Platform", hours: 3 },
  { date: "2027-01-20T00:00:00Z", week: 19, phase: "Payments + PDFs", focus: "Learn: Stripe/payment concepts, PDF generation, document workflows", practice: "Take notes, code examples yourself, then solve 2–3 small exercises.", projectTarget: "Start Will/Document Platform", hours: 3 },
  { date: "2027-01-21T00:00:00Z", week: 19, phase: "Payments + PDFs", focus: "Practice: Stripe/payment concepts, PDF generation, document workflows", practice: "Implement a small feature without following a tutorial; debug and test it.", projectTarget: "Start Will/Document Platform", hours: 3 },
  { date: "2027-01-22T00:00:00Z", week: 19, phase: "Payments + PDFs", focus: "Build: Payments + PDFs", practice: "Apply the week's concept directly to the project; commit your work.", projectTarget: "Start Will/Document Platform", hours: 3 },
  { date: "2027-01-23T00:00:00Z", week: 19, phase: "Payments + PDFs", focus: "Project-heavy day: Payments + PDFs. Apply this week's concepts.", practice: "Build for 2–3 focused hours; fix bugs; commit to Git.", projectTarget: "Start Will/Document Platform", hours: 3 },
  { date: "2027-01-24T00:00:00Z", week: 19, phase: "Rest / Catch-up", focus: "Rest. If needed, review notes or finish one unfinished task.", practice: "Optional 30–60 min light review", projectTarget: "No new build work", hours: 0 },
  { date: "2027-01-25T00:00:00Z", week: 19, phase: "Payments + PDFs", focus: "Learn: Stripe/payment concepts, PDF generation, document workflows", practice: "Take notes, code examples yourself, then solve 2–3 small exercises.", projectTarget: "Start Will/Document Platform", hours: 3 },
  { date: "2027-01-26T00:00:00Z", week: 20, phase: "Forms + APIs", focus: "Practice: Multi-step forms, conditional logic, validation, API integrations", practice: "Implement a small feature without following a tutorial; debug and test it.", projectTarget: "Build will-writing flow", hours: 3 },
  { date: "2027-01-27T00:00:00Z", week: 20, phase: "Forms + APIs", focus: "Build: Forms + APIs", practice: "Apply the week's concept directly to the project; commit your work.", projectTarget: "Build will-writing flow", hours: 3 },
  { date: "2027-01-28T00:00:00Z", week: 20, phase: "Forms + APIs", focus: "Learn: Multi-step forms, conditional logic, validation, API integrations", practice: "Take notes, code examples yourself, then solve 2–3 small exercises.", projectTarget: "Build will-writing flow", hours: 3 },
  { date: "2027-01-29T00:00:00Z", week: 20, phase: "Forms + APIs", focus: "Practice: Multi-step forms, conditional logic, validation, API integrations", practice: "Implement a small feature without following a tutorial; debug and test it.", projectTarget: "Build will-writing flow", hours: 3 },
  { date: "2027-01-30T00:00:00Z", week: 20, phase: "Forms + APIs", focus: "Project-heavy day: Forms + APIs. Apply this week's concepts.", practice: "Build for 2–3 focused hours; fix bugs; commit to Git.", projectTarget: "Build will-writing flow", hours: 3 },
  { date: "2027-01-31T00:00:00Z", week: 20, phase: "Rest / Catch-up", focus: "Rest. If needed, review notes or finish one unfinished task.", practice: "Optional 30–60 min light review", projectTarget: "No new build work", hours: 0 },
  { date: "2027-02-01T00:00:00Z", week: 20, phase: "Forms + APIs", focus: "Build: Forms + APIs", practice: "Apply the week's concept directly to the project; commit your work.", projectTarget: "Build will-writing flow", hours: 3 },
  { date: "2027-02-02T00:00:00Z", week: 21, phase: "Redis + GraphQL", focus: "Learn: Caching, sessions, queues, GraphQL fundamentals", practice: "Take notes, code examples yourself, then solve 2–3 small exercises.", projectTarget: "Add a small Redis/GraphQL demo", hours: 3 },
  { date: "2027-02-03T00:00:00Z", week: 21, phase: "Redis + GraphQL", focus: "Practice: Caching, sessions, queues, GraphQL fundamentals", practice: "Implement a small feature without following a tutorial; debug and test it.", projectTarget: "Add a small Redis/GraphQL demo", hours: 3 },
  { date: "2027-02-04T00:00:00Z", week: 21, phase: "Redis + GraphQL", focus: "Learn: Caching, sessions, queues, GraphQL fundamentals", practice: "Take notes, code examples yourself, then solve 2–3 small exercises.", projectTarget: "Add a small Redis/GraphQL demo", hours: 3 },
  { date: "2027-02-05T00:00:00Z", week: 21, phase: "Redis + GraphQL", focus: "Practice: Caching, sessions, queues, GraphQL fundamentals", practice: "Implement a small feature without following a tutorial; debug and test it.", projectTarget: "Add a small Redis/GraphQL demo", hours: 3 },
  { date: "2027-02-06T00:00:00Z", week: 21, phase: "Redis + GraphQL", focus: "Project-heavy day: Redis + GraphQL. Apply this week's concepts.", practice: "Build for 2–3 focused hours; fix bugs; commit to Git.", projectTarget: "Add a small Redis/GraphQL demo", hours: 3 },
  { date: "2027-02-07T00:00:00Z", week: 21, phase: "Rest / Catch-up", focus: "Rest. If needed, review notes or finish one unfinished task.", practice: "Optional 30–60 min light review", projectTarget: "No new build work", hours: 0 },
  { date: "2027-02-08T00:00:00Z", week: 21, phase: "Redis + GraphQL", focus: "Practice: Caching, sessions, queues, GraphQL fundamentals", practice: "Implement a small feature without following a tutorial; debug and test it.", projectTarget: "Add a small Redis/GraphQL demo", hours: 3 },
  { date: "2027-02-09T00:00:00Z", week: 22, phase: "Email + Storage", focus: "Learn: File uploads, object storage concepts, email workflows", practice: "Take notes, code examples yourself, then solve 2–3 small exercises.", projectTarget: "Add document/email features", hours: 3 },
  { date: "2027-02-10T00:00:00Z", week: 22, phase: "Email + Storage", focus: "Practice: File uploads, object storage concepts, email workflows", practice: "Implement a small feature without following a tutorial; debug and test it.", projectTarget: "Add document/email features", hours: 3 },
  { date: "2027-02-11T00:00:00Z", week: 22, phase: "Email + Storage", focus: "Build: Email + Storage", practice: "Apply the week's concept directly to the project; commit your work.", projectTarget: "Add document/email features", hours: 3 },
  { date: "2027-02-12T00:00:00Z", week: 22, phase: "Email + Storage", focus: "Learn: File uploads, object storage concepts, email workflows", practice: "Take notes, code examples yourself, then solve 2–3 small exercises.", projectTarget: "Add document/email features", hours: 3 },
  { date: "2027-02-13T00:00:00Z", week: 22, phase: "Email + Storage", focus: "Project-heavy day: Email + Storage. Apply this week's concepts.", practice: "Build for 2–3 focused hours; fix bugs; commit to Git.", projectTarget: "Add document/email features", hours: 3 },
  { date: "2027-02-14T00:00:00Z", week: 22, phase: "Rest / Catch-up", focus: "Rest. If needed, review notes or finish one unfinished task.", practice: "Optional 30–60 min light review", projectTarget: "No new build work", hours: 0 }
];

async function seed() {
  console.log(`🌱 Seeding ${studyDays.length} DevTrack study days...`);

  let created = 0;
  let skipped = 0;

  for (const studyDay of studyDays) {
    const existing = await db.orm.public.StudyDay
      .where({ date: studyDay.date })
      .first();

    if (existing) {
      console.log(`⏭️ Skipped ${studyDay.date} — already exists`);
      skipped++;
    } else {
      await db.orm.public.StudyDay.create(studyDay);
      created++;
    }
  }

  console.log(`✅ Created ${created} study days.`);
  console.log(`⏭️ Skipped ${skipped} existing study days.`);
}

seed()
  .catch((error) => {
    console.error("❌ Seed failed:");
    console.error(error);
    process.exit(1);
  });
